### ISSUE TITLE
La ventana gráfica no se actualiza en tiempo real

### ISSUE THREAD

**Issue by enel9** [PabloHorno/GestorDeHorasIssiues#12]
La ventana de las barritas de progreso no se actualiza si está desplegada. Sólo se actualiza cuando se despliega por lo que las barritas nunca crecen hasta que no la ocultas y le das a mostrar de nuevo.

**Comment by PabloHorno** [comment]
Actualización de gráfica cada segundo, solo si se esta mostrand.
