### ISSUE TITLE
Descansos por defecto de 15min todos los días

### ISSUE THREAD

**Issue by enel9** [PabloHorno/GestorDeHorasIssiues#16]
Sería ideal que el tiempo de los descansos que sale por defecto sean 45min de lunes a jueves y de 15 minutos los viernes. Ahora mismo (v1.15) salen siempre por defecto de 15 minutos.
También estaría bien dejar configurable el tiempo por defecto de lunes a jueves y de los viernes para que salga por defecto un tiempo personalizado.

**Comment by PabloHorno** [comment]
Solucionado
