### ISSUE TITLE
Agrupación por semanas

### ISSUE THREAD

**Issue by enel9** [PabloHorno/GestorDeHorasIssiues#17]
Es preferible que la agrupación de varios días en una sola barra corresponda con una semana en lugar de 5 días, porque se puede dar el caso de comenzar los registros un miércoles y entonces agrupa en una barra de miércoles a miércoles cuando lo natural será que agrupe de lunes a viernes. Esto no es muy prioritario, pero molaría más

**Comment by PabloHorno** [comment]
Hecho para la release v1.16
Ahora las semanas se cierran por semanas. Si la semana se cierra completa se pone de color gris si no, se deja un gris mas oscuro.
